### ISSUE TITLE
Install-SafeguardPatch uses too much memory

### ISSUE THREAD

**Issue by bnicholesdell** [OneIdentity/safeguard-ps#142]
The Install-SafeguardPatch cmdlet loads the entire patch into memory before uploading it to the Safeguard appliance.  With the current size of the patches, it causes the client to consume well over 1G of memory.  This is a problem for small clients or VMs that have not been configured with large amounts of memory.

**Comment by petrsnd** [comment]
I have discovered that there is a way to do this, but it will be pretty difficult from PowerShell.  The problem here is that the patch install from the safeguard-ps client uses an HTTP POST to stage the patch.  An HTTP POST is a single HTTP request with a content-length header, so the basic PowerShell primitives load the entire patch into memory then send it in the HTTP request.  This can be done through a stream that simultaneously reads from disk and writes to the socket in the HTTP request, but there some of the details will have to be handled manually in C# code that gets embedded in the PowerShell modules.

**Comment by bnicholesdell** [comment]
I found some additional information about this which may help to reduce the memory problem in the current implementation. I have noticed that if I install a patch, the memory footprint will jump to the size of the patch plus whatever memory was being used previously.  After the patch has been installed, the powershell command window does not release the memory.  

Suggestion #1- Run the reading in the patch file and uploading the patch in a different powershell process from the actual upgrade and monitoring.  Then once the patch uploading is done, the powershell process can be terminated and release the memory.

I also noticed that if the patch fails during the upload, starting a new upload will double the memory footprint.  Apparently, the previous patch is not being cleaned up properly.  I found this by attempting to upload a test patch on a prod deployment or vice-versa.

Suggestion #2 - Completely clean up a failed patch upload.  If suggestion #1 is implemented, #2 should come for free.
