### ISSUE TITLE
Enhancement Requests: Connect-Safeguard

### ISSUE THREAD

**Issue by Eric2XU** [OneIdentity/safeguard-ps#173]
1) When using GUI Switch still pass through Username field 
2) Currently it takes domain/realm via pipeline but not via a named parameter, create named parameter and allow pass thru to GUI
3) Allow for $MySessionVar = Connect-Safeguard currently it turns nothing, also ensure the returned variable is a PSObject not a hashtable like the current $SafeguardSession

**Comment by petrsnd** [comment]
@Eric2XU,

Thanks for using safeguard-ps and thanks for the feedback.

(1) is a really good suggestion, but I haven't figured out a good way to do it yet.  Currently, the browser window just loads up without any context.  I'm not sure how much control I have over the DOM as it's loading, but then again I haven't tried.  It may be possible.

On (2), I'm not sure what you mean.  `Connect-Safeguard` is taking the domain/realm via pipeline?

For (3), we have an option to just return an access token using the `-NoSessionVariable` parameter, but then you lose some of the other session elements, such as which appliance you are talking to and whether or not you want to strictly validate TLS.  We could talk about your use case and potentially create another parameter that returns what you're looking for in a PSObject.

**Comment by Eric2XU** [comment]
Sorry for the delay....

#2.... Connect-Safeguard | what I am trying to say is in the example on the readme it says to pass two arguments in the first being the domain/realm and the other being the account you want to logon as. However these should really be parameters to connect-safeguard. My suggestion -domain and -username. I type "connect-safeguard -" and keep tabbing but never find anything like domain or username. Nor does the get-help command show me any other then the positional arguments vs named parameters. 

#3... great to see we can do this with that parameter. I just didnt know, this is somewhat unstandard from the way other companies are doing connect-module commands. I would recommend checking out the connect-azureAD cmdlets.  https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0 however knowing how to do this I am totally fine. I do think the readme should have this information in it.

**Comment by petrsnd** [comment]
@Eric2XU 

(2) We can't use domain/realm, because Safeguard isn't only used with Active Directory.  The parameter you are looking for is `-IdentityProvider`, which might be a domain/realm, but it might also be local or RADIUS or something else.

(3) Unless I'm missing something the `Connect-AzureAD` cmdlets create a session, just like `Connect-Safeguard`.  I don't see any examples on that link where `Connect-AzureAD` is returning a token, but maybe I'm looking in the wrong place.

**Comment by Eric2XU** [comment]
Yup -IdentityProvider was it. 

(3) I guess I was thinking of another MSFT module although connect-azureAD does return a object (just not a token within the object)

**Comment by petrsnd** [comment]
This will be tracked as an enhancement request to honor identity provider and user name switches when using the gui switch.

**Comment by Kevin-Andrew** [comment]
@petrsnd , for number 1:
> When using GUI Switch still pass through Username field

You may be able to change the initial URL that is used when first opening the web browser to include the query string `login_hint`, and then the username parameter value from PowerShell.  For example:
```
https://172.21.21.4/RSTS/Login?Response_type=token&redirect_uri=https://172.21.21.4/service/appliance/swagger/ui/index&login_hint=superadmin&primaryProviderID=local
```

(The `primaryProviderID` parameter is obviously optional.)

**Comment by petrsnd** [comment]
I added the login hint.
We are not planning to add anything else from these enhancement requests.

**Comment by Kevin-Andrew** [comment]
You may specify your PowerShell command with an explicit `-Username` parameter like the following:
![image](https://user-images.githubusercontent.com/22459191/68233561-a3e2e000-ffbc-11e9-88c4-9d98ce8929dc.png)

And the resulting GUI will be:
![image](https://user-images.githubusercontent.com/22459191/68233594-b230fc00-ffbc-11e9-9216-a3848f575155.png)

Here, since this is the first time the login page was loaded, you must choose an Authentication Provider from the drop down list.  For subsequent times, the previously used provider will be pre-selected.  However, that is based on a cookie, which may get cleaned up if you clear the IE cache.

Or, if you also know the ID of the intended Authentication Provider, you can rely on the positional parameters and issue a command like the following:
![image](https://user-images.githubusercontent.com/22459191/68234169-e78a1980-ffbd-11e9-9c50-634382c4235e.png)

Here, we specified both the primary authentication provider ID `ad3`, and the username.  This results in the following GUI:
![image](https://user-images.githubusercontent.com/22459191/68234243-0688ab80-ffbe-11e9-8ac8-a3f0b1707c7c.png)

Unfortunately in both of these cases, you'll notice that the prepopulated username field is still showing the placeholder text behind the username.  Also note that the cursor focus is in the username field.  This will be corrected in the next version of Safeguard, such that you will end up with:
![image](https://user-images.githubusercontent.com/22459191/68234383-55cedc00-ffbe-11e9-8a11-60f9192d64d2.png)
