### ISSUE TITLE
Support -Gui parameter on PowerShell Core

### ISSUE THREAD

**Issue by Eric2XU** [OneIdentity/safeguard-ps#346]
I am running more and more workloads on PowerShell core, its time for Quest's Safeguard team to take the step and support PowerShell 7. 

Currently I get this error: 
![image](https://user-images.githubusercontent.com/12671152/129015420-9cd708ae-34de-4d54-a7ff-f5e1d077241d.png)

**Comment by petrsnd** [comment]
@Eric2XU The problem with the -Gui parameter is that it loads a web view control from inside the .NET framework to run the browser interaction.  That same component isn't available in PowerShell Core.  The most common reasons to use the -Gui option are for 2FA and for federation.  Which use case are you using?

For 2FA, there is a chance we could get a command-line only situation working.  This issue is being tracked as #131.  For federation, it is a little more complicated.  We have some ideas about some things that might work, but it will take some time to research and so they haven't been as high of a priority as other issues.

**Comment by petrsnd** [comment]
@Eric2XU, you could try https://www.powershellgallery.com/packages/safeguard-ps/6.11.26706-pre to see if it works for you.  That functionality will be the 6.11 release in a couple weeks.

**Comment by Eric2XU** [comment]
so I did notice a popup message for Royal TS that I have in the script is now textual vs GUI but I still got stopped at the same error message: 

This -Gui parameter is not supported in PowerShell Core

Is there a different parm I should use now?

**Comment by Eric2XU** [comment]
Hey just checking in. I am stuck on my Macbook Pro for a few weeks and its killing me to manually check out my creds every 4 hours and cut and paste the creds around. 

I am currently on 6.11.30528 and still get the same This -Gui parameter is not supported in PowerShell Core. 

You mentioned its in there now, do I need to use a new parm?

**Comment by Eric2XU** [comment]
I figured it out, use -twofactor instead... this works for now but when Starling goes away and I am forced to use SAML to another provider for MFA we will need the -gui switch, please make sure thats in place before sunset of starling.

**Comment by petrsnd** [comment]
I'm adding a new -Browser option that logs you in using the default browser.  It works on PowerShell Core on Windows.  I haven't tested it yet on other platforms.  It will be in the 6.12 release.
